
name: Compilation Workflow

on: [push, pull_request]

jobs:
  build:
    env:
      GO111MODULE: auto
      TARGET: amd64
        
    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-18.04, ubuntu-16.04]
        
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout project  
      uses: actions/checkout@v2
      
    - name: Copy SourceCode to GoPath
      run: mkdir -p $HOME/go/src/github.com/sodafoundation && cp -r ../nbp $HOME/go/src/github.com/sodafoundation/
      
    - name: Build
      run: make

    - name: Test & Coverage
      run: go test -v github.com/sodafoundation/nbp/csi/... -cover
